site_name: Kascas Blog
# site_url: https://mydomain.org/mysite
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant.progress
    - toc.follow
    # - toc.integrate
    - navigation.top
    - content.code.copy
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

plugins:
  - search:
      lang:
        - en
        - zh
  - blog:
      archive_date_format: MMMM yyyy
      blog_toc: true
  - tags
  - glightbox
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
exclude_docs: |
  Petri Net/*
nav:
  - 主页: index.md
  - 大模型:
      - Transformer: NLP/1 Transformer.md
  - 深度学习:
      - 基础知识: DL/1 基础知识.md
  - 强化学习:
      - 基础知识: RL/1 基础知识.md
      - 经典算法: RL/2 经典算法.md
      - 常用技巧: RL/3 常用技巧.md
      - 多智能体强化学习: RL/4 多智能体RL.md
  - 实用工具:
      - Cherry Studio使用指南: Tools/AI Tools/Cherry Studio.md
      - Zotero+LLM使用指南: Tools/AI Tools/Zotero+LLM.md
